### ISSUE TITLE
Opam is installed when already present in the user's system

### ISSUE THREAD

**Issue by tmattio** [tarides/ocaml-platform-installer#96]
After installing ocaml-platform on macOS Monterey (on Arm64), opam has been installed in `/usr/local/bin/opam` even if it was already in `/opt/homebrew/bin/opam`

**Comment by Julow** [comment]
We need to stop running the installer script as root to reliably query `which opam` (otherwise, the PATH might be changed by `sudo`.
This means that we need to call `sudo` within the script, removing the possibility for users that don't have `sudo` to log as root themselves.

An alternative to this would be to submit a homebrew package, ditching the installer script for macos users.

**Comment by tmattio** [comment]
Could we run `opam --version` and if it succeeds we skip the installation?

**Comment by panglesd** [comment]
Could we install opam (for root) if it is installed locally for the user?

If we consider that the installer is meant for installing `opam` for all users, I think it makes sense.

Also, I think this is what the `opam` installer script does (checking with `command -v opam`).

**Comment by Julow** [comment]
The Opam installer is not run as root, it uses sudo internally, that's what we should do.

**Comment by panglesd** [comment]
Closed by #102.
